update dal docs: grant/revoke/set-role
matrixorigin/matrixorigin.io pull request #123
Opened 2022-11-16 08:08 UTC by lacrimosaprinz

2022-11-17 02:25 UTC, domingozhang approved these changes

2022-11-17 06:52 UTC, LiSong0214 approved these changes

2022-11-17 15:48 UTC, dengn requested changes

2022-11-17 15:48 UTC, dengn commented on docs/MatrixOne/Overview/matrixone-feature-list.md
> +| UNIQUE KEY                           | Y, Syntax only implementation   |
Unique key is not syntax only implementation

2022-11-21 01:37 UTC, dengn approved these changes

2022-11-21 01:37 UTC, merged