update load-data/load-s3/basic-sql/show-account docs
matrixorigin/matrixorigin.io pull request #283
Opened 2023-02-16 09:10 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #
https://github.com/matrixorigin/matrixorigin.io/issues/268
## What this PR does / why we need it:

2023-02-16 09:20 UTC, lacrimosaprinz commented
@XuPeng-SH   why the check failed?

2023-02-22 02:13 UTC, dengn requested changes

2023-02-22 02:13 UTC, dengn commented on docs/MatrixOne/Develop/import-data/bulk-load/0.7-load-s3.md
> +## Method 1: LOAD DATA
Load from s3 has also the parallel feature now.

2023-03-01 04:42 UTC, dengn approved these changes

2023-03-01 04:46 UTC, merged