modify 0.8 docs for issue7727/6611
matrixorigin/matrixorigin.io pull request #296
Opened 2023-03-03 10:19 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-03-06 08:26 UTC, zengyan1 approved these changes

2023-03-07 02:08 UTC, dengn requested changes

2023-03-07 02:08 UTC, dengn commented on docs/MatrixOne/Reference/Data-Types/0.8-data-types.md
> +## **Decimal Types(Beta)**
this (beta) can be removed now

2023-03-07 03:08 UTC, dengn approved these changes

2023-03-07 03:08 UTC, merged